$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'brazilian-utils/cpf-utils'
require 'brazilian-utils/cep-utils'
require 'brazilian-utils/cnh-utils'
require 'brazilian-utils/cnpj-utils'
require 'brazilian-utils/currency-utils'
require 'brazilian-utils/date-utils'
require 'brazilian-utils/email-utils'
require 'brazilian-utils/legal-nature-utils'
require 'brazilian-utils/legal-process-utils'
require 'brazilian-utils/license-plate-utils'
require 'brazilian-utils/phone-utils'
